# Configuración del planeta.

opciones:
  # Debug activado o no:
  debug:	false
  info:		true
  
  # Máximo de posts por autor:
  maxposts:     3
  
  # Directorio de salida:
  outdir:	htdocs
  
  # Fichero del planeta:
  outfile:	index.html
  
  # Cada cuanto se refresca el planeta, mediante cron o lo que sea:
  refresco:	15m
  
meta:
  titulo:	Planeta Debian Venezuela
  owner:	Webmaster Debian Venezuela
  email:	webmaster@debian.org.ve
  descripcion:  Sitio que agrupa a los desarrolladores/mantenedores de Debian en Venezuela
  keywords:     software, libre, cultura, geek, linux, gnu, debian
  link:         http://planeta.debian.org.ve

  # Una imagen para icono general del feed rss.
  icono:	/glx/planeta.png
  lenguaje:     es-es

# Lista de feeds y avatares:
feeds:
  juan.angulo:
    url:    http://apostols.net/?feed=rss2
    email:  apostols@gmail.com
    avatar: apostols.png
    name:   Juan Angulo Moreno
  jose.luis.rivas:
    url:    http://ghostbar.ath.cx/tag/planeta-debian/feed/
    email:  ghostbar@debian.org.ve
    avatar: ghostbar.png
    name:   José Luis Rivas
  christian.sanchez:
    url:    http://blog.g013m.com.ve/index.php?/feeds/index.rss2
    email:  csanchez@unplug.org.ve
    avatar: planeta.png
    name:   Christian Sánchez
  alberto.capella:
    url:    http://alberkman.unplug.org.ve/feed/
    email:  alberkman@gmail.com
    avatar: alberkman.png
    name:   Alberto Capella
  bureado:
    url:    http://bureado.com/rss.xml
    email:  bureado@debian.org
    avatar: planeta.png
    name:   José Parrella
  ecrespo:
    url:    http://feeds.feedburner.com/LaLibertadDeDesarrollarNoTienePrecio
    email:  ecrespo@gmail.com
    avatar: planeta.png
    name:   Ernesto Crespo
  titacgs:
    url:    http://blog.titacgs.com.ar/category/debian/feed/
    email:  vanecgs@gmail.com
    avatar: planeta.png
    name:   Vanessa Gutierrez
  muammar:
    url:    http://muammar.me/blog/category/debian/feed/rss/
    email:  muammarelkhatib@gmail.com
    avatar: muammar.jpg
    name:   Muammar El Khatib
#  mogaal:
#    url:    http://blog.mogaal.com/?feed=rss2
#    email:  garridomota@gmail.com
#    avatar: mogaal.png
#    name:   Alejandro Garrido Mota
  gerard0:
    url:    http://feeds.feedburner.com/gerardocc
    email:  gcurier@gmail.com
    avatar: planeta.png
    name:   Gerardo Curiel
  Miguel:
    url:    http://miguel.cc/blog/index.rss
    email:  miguel@miguel.cc
    avatar: planeta.png
    name:   Miguel Landaeta
  Silverdog:
    url:    http://blog.silverdog.com.ve/category/linux/feed
    email:  silverdog@gmail.com
    avatar: planeta.png
    name:   Carlos Silombria
#  e1th0r:
#    url:    http://e1th0r.gulmer.org.ve/?feed=atom
#    email:  e1th0r@gmail.com
#    avatar: planeta.png
#    name:   Héctor Colina
